### ISSUE TITLE
Option to disable camera

### ISSUE THREAD

**Issue by wisechengyi** [apockill/RobotGUIProgramming#14]
Currently once camera is selected there does not seem to be a way to turn it off and it burns a decent portion of os resources. If you are okay with the idea, I can send out a PR. 

Thanks,
Yi

**Comment by apockill** [comment]
Hi Yi, how would you propose the change? Perhaps a button on the CameraWidget that pauses the VideoStream main loop? I'm definitely open to the idea.

**Comment by wisechengyi** [comment]
How about under "Devices" where it is initially setup? and add a disable button. So the place would be consistent in terms of scanning for/turning on/off some devices.

**Comment by apockill** [comment]
Ah I see. Sure, maybe a button next to "Scan for Cameras" that's just "Disconnect Camera" if you have a camera currently set in the settings it would simply turn it to None, and then tell the VideoStream to disconnect?
