### ISSUE TITLE
Any advice for a webcam? 

### ISSUE THREAD

**Issue by joihn** [apockill/RobotGUIProgramming#21]
I have the choice between a cheap camera (720p, 3Mpx) or a more expensive one (which output 1920x1080). 
Is it worth taking a high quality camera for this software? 

Thanks for your job :)

**Comment by wisechengyi** [comment]
hi @joihn, please see https://forum.ufactory.cc/t/camera-recommendation/440

**Comment by joihn** [comment]
okay thanks !
