### ISSUE TITLE
Arm not going low enough

### ISSUE THREAD

**Issue by joihn** [apockill/RobotGUIProgramming#24]
Hi,

When an object is recognised and the software try to automatically pick it up, it oftently stop 1cm on top of it. ( even though I made the uarm calibration correctly).

I suggets lowering the ground value, or getting a tough feedback via the tip sensor

**Comment by apockill** [comment]
Hi Joihn,

That's an interesting issue. I don't have a "ground" value persay, the robot should generally move downwards until the tip sensor is pressed, or it reaches a value that is far below the "ground" value set in the calibration. I assume your robot is touching the ground when you do the calibration?

There might be something in the robots firmware preventing it from going to a Z value lower than that, as well.

**Comment by joihn** [comment]
Hi, thanks for the fast response 
Yes I did the calibration correctly. 

in fact I'm using ufactory fork with their firmware, not yours. 

When I give a "move to"  command, the robot is able to touch the ground, and even go under. 

I will inspect the issue when I can :)
