### ISSUE TITLE
cinematic motion algorithm

### ISSUE THREAD

**Issue by mkeyno** [apockill/RobotGUIProgramming#25]
hi, sorry to open ticket for my question , but actually I'm little lost to find the methods can convert input location (Cartesian , polar) to the optimized cinematic motions of each axis? for example how to defined the best path from A to B coordinates and how it converted to the cinematic motion for each axis? what is the optimization function & type ?how to define cinematic motion parameters of specific arms? I really appreciated for your hint

**Comment by apockill** [comment]
Hi, unfortunately that's something that's best done directly through the firmware. uArm Creator Studio sends cartesian coordinates through Serial and never deals with the cinematic motions.

If you need those motions, you might have to build it on the uArm Firmware and upload using Arduino IDE.
