### ISSUE TITLE
Cross Platform Compatibility - Hard coded directory separators

### ISSUE THREAD

**Issue by storm255** [apockill/RobotGUIProgramming#5]
Hi.

Just downloaded it to have a poke around as it looks very impressive on the demo video for rapid development.

I might have done something wrong, but I had to do a quick find and replace on the directory string separators to get it up and running on Linux.  Haven't investigated further but it might be that os.path.join() could be used for future portability.

Python 3.5.2
PyQt5 5.6.1
OpenCV 3.1.0-3

Great work.  Looking forward to exploring.

**Comment by apockill** [comment]
That's very interesting, I hadn't thought of that problem. Does your solution work?

**Comment by storm255** [comment]
It worked to get it up and running in my environment just doing a simple find and replace on the double backward slashes with a single forward slash (I think there were 12 replacements), but to be cross platform I think it would just need the 

`resourcesLoc = 'Resources'`
`settings_txt = os.path.join(resourcesLoc, 'Settings.txt')`

in the appropriate places.

I can do a pull request later if that would help, but I am on a project for the next few weeks.

Mark.

**Comment by apockill** [comment]
Thank you, I'm glad to hear that worked. I'll get right on that.

**Comment by apockill** [comment]
Okay, so I combed through the project and got rid of every filename concatenation, then thoroughly tested it. If you could run it and tell me if I missed anything, I'd be quite grateful!

Also, were there any steps I missed in the build instructions on my readme? Thanks!

**Comment by storm255** [comment]
All good from my perspective.  Like I said, I haven't done anything with it yet, but it opens successfully here on Linux.  I already had the requirements installed so no problem from that point of view as well.  

Found the cameras without problem.  Will have to wait till I get home to hook up to some hardware and test a few things.

Thanks for being so responsive.  Have a great day.

**Comment by apockill** [comment]
If you get the chance, you can try the object recognition and tracking without needing any hardware attached. Just click "Resources", "New Vision Object" and follow the steps. 

It's fun to experiment with the tracking
