### ISSUE TITLE
Exception when creating vision object on Linux

### ISSUE THREAD

**Issue by velovix** [apockill/RobotGUIProgramming#7]
An exception occurs after selecting an area when creating a new vision object. The exception is `The data should normally be NULL!`.

I fixed it by compiling OpenCV source directly from Github. The newest release of OpenCV 3 does not have the fix yet.

**Comment by apockill** [comment]
Okay, good to know. For now we'll have to compile openCV into a binary for any Linux releases to have any potential issues with package managers releasing the correct versions of OpenCV.

Hopefully they fix the issue soon.
